### ISSUE TITLE
Encoder for Steering-angle

### ISSUE THREAD

**Issue by Cirromulus** [pilsbot/pilsbot#13]
- [x] Adapter for potentiometer
- [x] Pro Micro for Ros Serial to publish Pot-Value
- [x] Endstops
- [x] Driver for Pot/Endstop calibration
- [X] Filter an pre-processed steering angle topic provider

**Comment by DarthBubi** [comment]
Use a Potentiometer on top of the stering axle.
Will be connected to the endanschlag

**Comment by DarthBubi** [comment]
The steering angle encoder got damaged while testing the Pilsbot. @Cirromulus Needs to be repaired.

**Comment by Cirromulus** [comment]
This is done.

**Comment by Cirromulus** [comment]
Nice, this works conceptually. Need to fix the mounting bracket, though.
