### ISSUE TITLE
Register an appropriate website

### ISSUE THREAD

**Issue by Cirromulus** [pilsbot/pilsbot#16]
Domain is intentionally left out so no crazy registrars take our precious domain!!111

**Comment by DarthBubi** [comment]
I registered pilsbot.de. We just need some place where it should point.

**Comment by Cirromulus** [comment]
let it point to 
```
A     212.227.8.137
AAAA  2001:8d8:1800:dd::1
```

**Comment by Cirromulus** [comment]
Done.
