### ISSUE TITLE
Add wiki on how to get started

### ISSUE THREAD

**Issue by Cirromulus** [pilsbot/pilsbot#18]
It would be helpful if we had a quick "getting started" wiki entry for how to build ROS system.

**Comment by Cirromulus** [comment]
I know, this is very rudimentary, but this project is pretty much WIP.
Info is currently found under https://github.com/pilsbot/pilsbot/wiki/Installation

**Comment by PimpMyPizza** [comment]
And [here](https://github.com/pilsbot/workspace). Adding some images would be nice too
