### ISSUE TITLE
GPS include into microcontroller

### ISSUE THREAD

**Issue by Cirromulus** [pilsbot/pilsbot#19]
@PimpMyPizza, you said something of an existing driver for your GPS module?

- [ ] Add GPS serial to endstop-microcrontroller
- [ ] Publish shit to ROS

**Comment by PimpMyPizza** [comment]
Yes: http://wiki.ros.org/ublox

**Comment by Cirromulus** [comment]
With the new USB GPS, we don't need this anymore.
