### ISSUE TITLE
Add some lights to the chassis

### ISSUE THREAD

**Issue by DarthBubi** [pilsbot/pilsbot#21]
A test drive at dusk showed that we need some lights on the Pilsbot. Additionally, blinkers seem to be a nice addition for later stages of the development.
On the hardware side, WS2812 LEDs are a reasonable choice.

**Comment by Cirromulus** [comment]
I have enough WS2812 for the bot.
Use cases: Indicators, brake-light, front light. Party-Mode.
Rosserial is available for the ubiquitous ESP-01. As lighting is non-critical, i suppose a wireless connection.
