### ISSUE TITLE
Setup a simulation enivronment

### ISSUE THREAD

**Issue by DarthBubi** [pilsbot/pilsbot#24]
For offline testing purposes it would be nice to have a simulation.

**Comment by DarthBubi** [comment]
The robot spawns in simulation see packages `pilsbot_simualtion` and `pilsbot_description`, but for some reason the plugins are not providing data. Needs further investigation.

**Comment by DarthBubi** [comment]
Plugins are working now. Seems like installing the  `gazebo_ros` package didn't install the plugins. Inertia and masses are currently not correct, so the bot is driving strangely.

**Comment by Cirromulus** [comment]
First Simulation tests with new `acker_diff_drive` seem promising
