### ISSUE TITLE
Automatic installation of dependencies

### ISSUE THREAD

**Issue by PimpMyPizza** [pilsbot/pilsbot#25]
- We use several tools/ROS packages in the project
- Some of these tools have dependencies (for example ros2-web-bridge depends on nodejs, that depends on nvm under ubuntu. The project in a whole depends on ros2 and vcstool)
- It would be cool to automatically install the dependencies depending on the OS used in order to avoid 10000 installation tutorials
- I'm not quite sure which solution is the best to do that.

**Comment by Cirromulus** [comment]
I am not sure about that. I usually go with an installation script, but these tend to age unwell.
In the current state of "rapid" development, maybe one installs the packages on-the-go as errors come.

**Comment by PimpMyPizza** [comment]
rel: #26
