### ISSUE TITLE
Setup CI/Dockerfile at least for compiling

### ISSUE THREAD

**Issue by hemker** [pilsbot/pilsbot#27]

**Comment by DarthBubi** [comment]
At least for the hardware stack, a Dockerfile exists. This is actually needed, because the current JetPack does not support ROS2 Foxy.

**Comment by DarthBubi** [comment]
Also, we set up a Docker Hub user for our project. See [here](https://hub.docker.com/u/pilsbot).

**Comment by Cirromulus** [comment]
With the new and shiny https://github.com/pilsbot/pilsbot_vscode_ws, this is possible :)
