### ISSUE TITLE
Jetson gets a bit hot, add a fan

### ISSUE THREAD

**Issue by Cirromulus** [pilsbot/pilsbot#37]
We need more fans

**Comment by DarthBubi** [comment]
Order is placed w/ mounting screws.

**Comment by DarthBubi** [comment]
Fan arrived, will test mounting on my own Jetson Nano first.

**Comment by Cirromulus** [comment]
Problems arose.
Not with the fan, but unmounted jetson anyways. Now PWM-Controlled noctua is on.
